### ISSUE TITLE
编译成功，但是运行不成功

### ISSUE THREAD

**Issue by chago** [baikaishiuc/fastvm#7]
按照文档描述的流程编译后，单独运行程序没问题，执行-df命令出错

![20200713180321](https://user-images.githubusercontent.com/2239471/87292273-28660500-c533-11ea-90ac-94110ad1c851.png)

![20200713180416](https://user-images.githubusercontent.com/2239471/87292367-4c294b00-c533-11ea-8e8c-25515c43c43e.png)

![20200713180526](https://user-images.githubusercontent.com/2239471/87292496-77139f00-c533-11ea-88f7-43ba73d1fc72.png)

**Comment by baikaishiuc** [comment]
你好，麻烦发一下崩溃堆栈

**Comment by baikaishiuc** [comment]
> 按照文档描述的流程编译后，单独运行程序没问题，执行-df命令出错
> 
> ![20200713180321](https://user-images.githubusercontent.com/2239471/87292273-28660500-c533-11ea-90ac-94110ad1c851.png)
> 
> ![20200713180416](https://user-images.githubusercontent.com/2239471/87292367-4c294b00-c533-11ea-8e8c-25515c43c43e.png)
> 
> ![20200713180526](https://user-images.githubusercontent.com/2239471/87292496-77139f00-c533-11ea-88f7-43ba73d1fc72.png)

你好，麻烦发一下崩溃堆栈
